# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6e4af61c7385691ad8b19d8764720320a80266cede4b350c58823319794ceeb2481ff8dcf1f8082b5e78a869b6339f544c4096751842c9bc717429ba30fe525

test:
  secret_key_base: d40e05101d7fea07ae2c908855e114a4ec5666de06efd53ef7958e08d861c744381bf62b54c896379e6db7dab82ff2b4d0dfb7ed3b523a22932dc0f2540ad624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
